@file:Suppress("unused")

package cyou.shinobi9.cirrus.network.packet

enum class CMD(val desc: String) {
    DANMU_MSG("收到弹幕"),
    SEND_GIFT("有人送礼"),
    SUPER_CHAT_MESSAGE("醒目留言"),
    SUPER_CHAT_MESSAGE_DELETE("删除醒目留言"),
    GUARD_BUY("有人上舰"),
    ACTIVITY_BANNER_RED_NOTICE_CLOSE(""),
    ACTIVITY_BANNER_UPDATE_V2(""),
    ACTIVITY_BANNER_UPDATE_BLS("BLS活动"),
    ACTIVITY_EVENT(""),
    ACTIVITY_MATCH_GIFT(""),
    ACTIVITY_RED_PACKET(""),
    BLOCK(""),
    CHANGE_ROOM_INFO("房间设置变更"),
    CLOSE(""),
    COMBO_END("COMBO结束"),
    COMBO_SEND("COMBO赠送"),
    CUT_OFF("直播强制切断"),
    DAILY_QUEST_NEWDAY(""),
    END(""),
    ENTRY_EFFECT("加入效果"),
    GUARD_LOTTERY_START(""),
    GUARD_MSG("舰队消息"),
    GUIARD_MSG(""),
    HOUR_RANK_AWARDS(""),
    EVENT_CMD("活动相关"),
    LIVE("开始直播"),
    LOL_ACTIVITY(""),
    LUCK_GIFT_AWARD_USER(""),
    MESSAGEBOX_USER_GAIN_MEDAL(""),
    NEW_ANCHOR_REWARD(""),
    NOTICE_MSG(""),
    PK_AGAIN(""),
    PK_END(""),
    PK_MATCH(""),
    PK_MIC_END(""),
    PK_PRE(""),
    PK_PROCESS(""),
    PK_SETTLE(""),
    PK_START(""),
    PREPARING("准备直播"),
    RAFFLE_END("抽奖结束"),
    RAFFLE_START("抽奖开始"),
    REFRESH(""),
    ROOM_ADMINS("管理员变更"),
    ROOM_REAL_TIME_MESSAGE_UPDATE("房间时间更新"),
    ROOM_ADMIN_ENTRANCE(""),
    ROOM_BLOCK_INTO(""),
    ROOM_BLOCK_MSG("房间封禁消息"),
    ROOM_BOX_MASTER(""),
    ROOM_CHANGE(""),
    ROOM_KICKOUT(""),
    ROOM_LIMIT(""),
    ROOM_LOCK(""),
    ROOM_RANK("周星榜"),
    ROOM_REFRESH(""),
    ROOM_SHIELD("房间屏蔽"),
    ROOM_SILENT_OFF("房间禁言结束"),
    ROOM_SILENT_ON("房间开启禁言"),
    ROOM_SKIN_MSG("房间皮肤消息"),
    ROUND(""),
    SCORE_CARD(""),
    SEND_TOP(""),
    SPECIAL_GIFT("特殊礼物消息 节奏风暴"),
    SUPER_CHAT_ENTRANCE(""),
    SUPER_CHAT_MESSAGE_JPN(""),
    SYS_GIFT("系统礼物,广播"),
    SYS_MSG("系统消息,广播"),
    TV_END("小电视抽奖结束"),
    TV_START("小电视抽奖开始"),
    USER_TOAST_MSG(""),
    WARNING(""),
    WEEK_STAR_CLOCK(""),
    WELCOME(" `老爷` 进入直播间"),
    WELCOME_ACTIVITY(""),
    WELCOME_GUARD(" `舰长` 进入直播间"),
    WIN_ACTIVITY(""),
    WISH_BOTTLE("许愿瓶"),

    ONLINE_RANK_COUNT(""),
    INTERACT_WORD("进入直播间"),

    UNKNOWN("待补充，暂时无法处理");

    companion object {
        val byCommand = values().associateBy { it.name }
    }
}
